### ISSUE TITLE
导入知识库数据出错

### ISSUE THREAD

**Issue by shoopman** [c121914yu/FastGPT#66]
硬件环境：Mac M2芯片
软件环境：pg, mongo用的docker部署，fastgpt使用pnpm。

在知识库--知识库数据--导入--手动/文件拆分都报一样的错误：
`
wait  - compiling /api/openapi/kb/pushData (client and server)...
event - compiled successfully in 156 ms (198 modules)
error: null value in column "model_id" of relation "modeldata" violates not-null constraint
    at Parser.parseErrorMessage (~/Work/ai/FastGPT/node_modules/.pnpm/registry.npmmirror.com+pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (~/Work/ai/FastGPT/node_modules/.pnpm/registry.npmmirror.com+pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (~/Work/ai/FastGPT/node_modules/.pnpm/registry.npmmirror.com+pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (~/Work/ai/FastGPT/node_modules/.pnpm/registry.npmmirror.com+pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 414,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (3, null, waiting, 64741167079cb0c39ba3e8d4, null, JDK 17已经于2021年3月16日如期发布。本文介绍JDK 17..., 发布版本说明\n' +
    '根据发布的规划，这次发布的 JDK 1..., 6474118c079cb0c39ba3e8e3).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'modeldata',
  column: 'model_id',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1968',
  routine: 'ExecConstraints'
}
`

麻烦帮忙看看是什么情况，谢谢！

**Comment by c121914yu** [comment]
3.7没有初始化数据库。具体看init.sql文件，清理掉model_id字段

**Comment by shoopman** [comment]
感谢，全流程已经跑通了。
原来我是按 [https://github.com/c121914yu/FastGPT/blob/main/docs/deploy/mac.md](https://github.com/c121914yu/FastGPT/blob/main/docs/deploy/mac.md) 来配置的，里面的SQL版本老的，所以有问题。
